### ISSUE TITLE
s/nonsecure/insecure/g

### ISSUE THREAD

**Issue by mnot** [mikewest/scheming-cookies#3]
it's bugging me :)

**Comment by mikewest** [comment]
Unfortunately, the choice was both intentional and not limited to this explainer (see https://www.w3.org/TR/secure-contexts/ for prior art).

"Non-secure" is meant to suggest a lack of security, as opposed to "insecure"'s connotation (in my head at least) of a positive assertion of violation (along with the ambiguity of "anxiety", etc). I guess it's not triggering the same distinction for you?

**Comment by mnot** [comment]
Nah, just you know, grammar.
